CREATE TABLE IF NOT EXISTS public.configuracionsistema (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clave text NOT NULL,
    valor text NOT NULL,
    fechaactualizacion timestamp with time zone NULL DEFAULT NOW(),
    descripcion text NULL,
    CONSTRAINT pk_configuracionsistema PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_configuracionsistema_clave ON public.configuracionsistema (clave);
