// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrestamosApi.Data;

#nullable disable

namespace PrestamosApi.Migrations
{
    [DbContext(typeof(PrestamosDbContext))]
    [Migration("20260112164609_AddCierreMesLog")]
    partial class AddCierreMesLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrestamosApi.Models.AportadorExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiasParaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("diasparapago");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("MontoPagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montopagado");

                    b.Property<decimal>("MontoTotalAportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montototalaportado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldopendiente");

                    b.Property<decimal>("TasaInteres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(3m)
                        .HasColumnName("tasainteres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("aportadoresexternos", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.Aporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaAporte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaaporte");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montoactual");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montoinicial");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_aportes_usuario");

                    b.ToTable("aportes", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.CierreMesLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEjecucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CierreMesLogs");
                });

            modelBuilder.Entity("PrestamosApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.CuotaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cobrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cobrado");

                    b.Property<string>("EstadoCuota")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estadocuota");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacobro");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechapago");

                    b.Property<decimal>("MontoCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montocuota");

                    b.Property<decimal>("MontoInteres")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoPagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montopagado");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("integer")
                        .HasColumnName("numerocuota");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldopendiente");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCuota")
                        .HasDatabaseName("idx_cuotas_estado");

                    b.HasIndex("FechaCobro")
                        .HasDatabaseName("idx_cuotas_fecha");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("idx_cuotas_prestamo");

                    b.HasIndex("PrestamoId", "NumeroCuota")
                        .IsUnique();

                    b.ToTable("cuotasprestamo", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.DistribucionGanancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaDistribucion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechadistribucion");

                    b.Property<bool>("Liquidado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("liquidado");

                    b.Property<decimal>("MontoGanancia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montoganancia");

                    b.Property<decimal>("PorcentajeAsignado")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentajeasignado");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("idx_distribuciones_prestamo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_distribuciones_usuario");

                    b.ToTable("distribucionesganancias", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.FuenteCapitalPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AportadorExternoId")
                        .HasColumnType("integer")
                        .HasColumnName("aportadorexternoid");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("MontoAportado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montoaportado");

                    b.Property<decimal>("PorcentajeParticipacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("porcentajeparticipacion");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("AportadorExternoId")
                        .HasDatabaseName("idx_fuentescapital_aportador");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("idx_fuentescapital_prestamo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_fuentescapital_usuario");

                    b.ToTable("fuentescapitalprestamo", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.MovimientoCapital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechamovimiento");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldoanterior");

                    b.Property<decimal>("SaldoNuevo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldonuevo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipomovimiento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("FechaMovimiento")
                        .HasDatabaseName("idx_movimientos_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_movimientos_usuario");

                    b.ToTable("movimientoscapital", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("comprobante");

                    b.Property<int?>("CuotaId")
                        .HasColumnType("integer")
                        .HasColumnName("cuotaid");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechapago");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodopago");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montopago");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("integer")
                        .HasColumnName("prestamoid");

                    b.HasKey("Id");

                    b.HasIndex("CuotaId")
                        .HasDatabaseName("idx_pagos_cuota");

                    b.HasIndex("PrestamoId")
                        .HasDatabaseName("idx_pagos_prestamo");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.PagoAportadorExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AportadorExternoId")
                        .HasColumnType("integer")
                        .HasColumnName("aportadorexternoid");

                    b.Property<string>("Comprobante")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comprobante");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechapago");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodopago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<decimal>("MontoCapital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montocapital");

                    b.Property<decimal>("MontoIntereses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("montointereses");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.HasKey("Id");

                    b.HasIndex("AportadorExternoId")
                        .HasDatabaseName("idx_pagosaportadores_aportador");

                    b.ToTable("pagosaportadoresexternos", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<int?>("CobradorId")
                        .HasColumnType("integer")
                        .HasColumnName("cobradorid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("DiaSemana")
                        .HasColumnType("text")
                        .HasColumnName("diasemana");

                    b.Property<bool>("EsCongelado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPrestamo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estadoprestamo");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaprestamo");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechavencimiento");

                    b.Property<string>("FrecuenciaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frecuenciapago");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montocuota");

                    b.Property<decimal>("MontoIntereses")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montointereses");

                    b.Property<decimal>("MontoPrestado")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montoprestado");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("montototal");

                    b.Property<int>("NumeroCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("numerocuotas");

                    b.Property<decimal>("PorcentajeCobrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(5m)
                        .HasColumnName("porcentajecobrador");

                    b.Property<decimal>("TasaInteres")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tasainteres");

                    b.Property<string>("TipoInteres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Simple")
                        .HasColumnName("tipointeres");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_prestamos_cliente");

                    b.HasIndex("CobradorId")
                        .HasDatabaseName("idx_prestamos_cobrador");

                    b.HasIndex("EstadoPrestamo")
                        .HasDatabaseName("idx_prestamos_estado");

                    b.HasIndex("FechaPrestamo")
                        .HasDatabaseName("idx_prestamos_fecha");

                    b.ToTable("prestamos", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.SmsCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("DiasEnvio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("diasenvio");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechamodificacion");

                    b.Property<string>("HorasEnvio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("horasenvio");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoDestinatario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipodestinatario");

                    b.Property<int>("VecesPorDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("vecespordia");

                    b.HasKey("Id");

                    b.ToTable("smscampaigns", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.SmsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("errormessage");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaenvio")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numerotelefono");

                    b.Property<int?>("SmsCampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("smscampaignid");

                    b.Property<string>("TwilioSid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("twiliosid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaEnvio")
                        .HasDatabaseName("idx_smshistory_fecha");

                    b.HasIndex("SmsCampaignId")
                        .HasDatabaseName("idx_smshistory_campaign");

                    b.ToTable("smshistory", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<decimal>("CapitalActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("capitalactual");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<decimal>("GananciasAcumuladas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gananciasacumuladas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordhash");

                    b.Property<decimal>("PorcentajeParticipacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("porcentajeparticipacion");

                    b.Property<string>("Rol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<decimal>("TasaInteresMensual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(3m)
                        .HasColumnName("tasainteresmensual");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UltimoCalculoInteres")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimocalculointeres");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PrestamosApi.Models.Aporte", b =>
                {
                    b.HasOne("PrestamosApi.Models.Usuario", "Usuario")
                        .WithMany("Aportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrestamosApi.Models.CuotaPrestamo", b =>
                {
                    b.HasOne("PrestamosApi.Models.Prestamo", "Prestamo")
                        .WithMany("Cuotas")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("PrestamosApi.Models.DistribucionGanancia", b =>
                {
                    b.HasOne("PrestamosApi.Models.Prestamo", "Prestamo")
                        .WithMany("Distribuciones")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrestamosApi.Models.Usuario", "Usuario")
                        .WithMany("Ganancias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrestamosApi.Models.FuenteCapitalPrestamo", b =>
                {
                    b.HasOne("PrestamosApi.Models.AportadorExterno", "AportadorExterno")
                        .WithMany("FuentesCapital")
                        .HasForeignKey("AportadorExternoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PrestamosApi.Models.Prestamo", "Prestamo")
                        .WithMany("FuentesCapital")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrestamosApi.Models.Usuario", "Usuario")
                        .WithMany("FuentesCapital")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AportadorExterno");

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrestamosApi.Models.MovimientoCapital", b =>
                {
                    b.HasOne("PrestamosApi.Models.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrestamosApi.Models.Pago", b =>
                {
                    b.HasOne("PrestamosApi.Models.CuotaPrestamo", "Cuota")
                        .WithMany("Pagos")
                        .HasForeignKey("CuotaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PrestamosApi.Models.Prestamo", "Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuota");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("PrestamosApi.Models.PagoAportadorExterno", b =>
                {
                    b.HasOne("PrestamosApi.Models.AportadorExterno", "AportadorExterno")
                        .WithMany("Pagos")
                        .HasForeignKey("AportadorExternoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AportadorExterno");
                });

            modelBuilder.Entity("PrestamosApi.Models.Prestamo", b =>
                {
                    b.HasOne("PrestamosApi.Models.Cliente", "Cliente")
                        .WithMany("Prestamos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrestamosApi.Models.Usuario", "Cobrador")
                        .WithMany("PrestamosComoCobrador")
                        .HasForeignKey("CobradorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Cobrador");
                });

            modelBuilder.Entity("PrestamosApi.Models.SmsHistory", b =>
                {
                    b.HasOne("PrestamosApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PrestamosApi.Models.SmsCampaign", "SmsCampaign")
                        .WithMany("HistorialSms")
                        .HasForeignKey("SmsCampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("SmsCampaign");
                });

            modelBuilder.Entity("PrestamosApi.Models.AportadorExterno", b =>
                {
                    b.Navigation("FuentesCapital");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PrestamosApi.Models.Cliente", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("PrestamosApi.Models.CuotaPrestamo", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PrestamosApi.Models.Prestamo", b =>
                {
                    b.Navigation("Cuotas");

                    b.Navigation("Distribuciones");

                    b.Navigation("FuentesCapital");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("PrestamosApi.Models.SmsCampaign", b =>
                {
                    b.Navigation("HistorialSms");
                });

            modelBuilder.Entity("PrestamosApi.Models.Usuario", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("FuentesCapital");

                    b.Navigation("Ganancias");

                    b.Navigation("Movimientos");

                    b.Navigation("PrestamosComoCobrador");
                });
#pragma warning restore 612, 618
        }
    }
}
