Build started...
Build succeeded.
START TRANSACTION;

ALTER TABLE prestamos ADD "EsCongelado" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE cuotasprestamo ADD "MontoCapital" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE cuotasprestamo ADD "MontoInteres" numeric NOT NULL DEFAULT 0.0;

CREATE TABLE "CierreMesLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Mes" integer NOT NULL,
    "Anio" integer NOT NULL,
    "FechaEjecucion" timestamp with time zone NOT NULL,
    "Resultado" text NOT NULL,
    CONSTRAINT "PK_CierreMesLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260112164609_AddCierreMesLog', '8.0.8');

COMMIT;


